import { supabase } from '@/integrations/supabase/client';

export async function sendSMS(phone: string | undefined | null, message: string): Promise<void> {
  if (!phone) return;
  try {
    const { error } = await supabase.functions.invoke('send-sms', {
      body: { to: phone, message },
    });
    if (error) console.error('[SMS] Failed to send:', error);
  } catch (err) {
    console.error('[SMS] Error:', err);
  }
}

export const SmsTemplates = {
  customerWelcome: (name: string) =>
    `Dear ${name}, welcome to DAG Clothing Pvt Ltd! We are delighted to have you as our valued customer. We look forward to serving you with the finest apparel. Thank you for choosing DAG Clothing!`,

  salesOrderCreated: (name: string, total: number, pdfUrl?: string) =>
    `Dear ${name}, thank you for placing your order with DAG Clothing Pvt Ltd! Your sales order of LKR ${total.toLocaleString()} has been successfully received and is being processed.${pdfUrl ? ` View your order here: ${pdfUrl}` : ''} We truly appreciate your trust in us. Thank you for choosing DAG Clothing!`,

  invoiceCreated: (name: string, invoiceNumber: string, total: number, pdfUrl?: string) =>
    `Dear ${name}, your invoice #${invoiceNumber} of LKR ${total.toLocaleString()} has been generated by DAG Clothing Pvt Ltd.${pdfUrl ? ` You may view and download your invoice here: ${pdfUrl}` : ''} We are grateful for your continued support. Thank you for choosing DAG Clothing!`,

  purchaseOrderCreated: (agencyName: string, orderId: string, total: number, pdfUrl?: string) =>
    `Dear Team, a new Purchase Order has been submitted by ${agencyName}. Order ID: ${orderId}, Total: LKR ${total.toLocaleString()}.${pdfUrl ? ` View PDF: ${pdfUrl}` : ''} Please review and process at your earliest convenience. - DAG Clothing Pvt Ltd`,

  purchaseOrderUpdated: (agencyName: string, orderId: string, total: number, pdfUrl?: string) =>
    `Dear Team, please note that Purchase Order ${orderId} from ${agencyName} has been revised. Updated Total: LKR ${total.toLocaleString()}.${pdfUrl ? ` View updated PDF: ${pdfUrl}` : ''} Kindly review the changes. - DAG Clothing Pvt Ltd`,

  collectionRecorded: (
    name: string,
    cashAmount: number,
    cheques: Array<{ chequeNumber: string; amount: number }>,
  ) => {
    const parts: string[] = [];
    if (cashAmount > 0) {
      parts.push(`Cash payment of LKR ${cashAmount.toLocaleString()}`);
    }
    cheques.forEach(c => {
      parts.push(`Cheque #${c.chequeNumber} of LKR ${c.amount.toLocaleString()}`);
    });
    const total = cashAmount + cheques.reduce((s, c) => s + c.amount, 0);
    return `Dear ${name}, we have successfully received your payment of LKR ${total.toLocaleString()} (${parts.join(' & ')}) at DAG Clothing Pvt Ltd. Your account has been updated accordingly. We sincerely appreciate your prompt payment. Thank you for choosing DAG Clothing!`;
  },
};
